cole/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("departamento/", include("departamento.urls")),
    path("perfil/", include("perfil.urls")),
    path("persona/", include("persona.urls")),
    path("contactos/", include("contactos.urls")),
    path("domicilios/", include("domicilio.urls")),
    path("personal/", include("personal.urls")),
    path("alumnos/", include("alumnos.urls")),
    path("", include("inicio.urls")),
]

contactos/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("lista_contactos/", views.contactos, name="contactos"),
]

perfil/urls.py
from django.urls import path
from . import views

app_name = "perfil"
urlpatterns = [
    path("login/", views.iniciar_sesion, name="login"),
    path("logout/", views.cerrar_sesion, name="logout"),
]

contactos/models.py
from django.db import models
from persona.models import Persona
# Create your models here.

class Contacto(models.Model):
	persona = models.ForeignKey(Persona, on_delete=models.SET_NULL,
        null=True, related_name="perss")
	numero = models.IntegerField(max_length = 16)

	def __str__(self):
		tex = "{0}-{1}"
		return tex.format(self.persona, self.numero)

	

contactos/views.py
from django.shortcuts import render
from .models import Contacto
# Create your views here.
def contactos(request):
    lista_contactos = Contacto.objects.all()
    return render(request, "contactos/contactos.html",{"lista_contactos":lista_contactos})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
	<title>{% block title %} {% endblock %}</title>
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600&family=Noto+Sans+JP&display=swap" rel="stylesheet"> 
	<link rel="stylesheet" type="text/css" href='{% static "css/estilos.css" %}'>

</head>
<body >
	<header>
		{% include 'navbar.html' %}
		<div class="contenedor-imagen">
                <a href="#blog">
                    <img src="https://images.unsplash.com/photo-1504384308090-c894fdcc538d?ixlib=rb-1.2.1&ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&auto=format&fit=crop&w=1950&q=80" alt="">
                </a>
        </div>
	</header>
	<div >
		{% block contenido %}
		{% endblock %}
	</div>
		
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</body>
</html>

templates/base_a.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<title>{% block title %} {% endblock %}</title>
</head>
<body style="background-color: #FFF5EE;">
	<header>
		{% include 'navbar_a.html' %}
		
	</header>
	<div >
		{% block contenido %}
		{% endblock %}
	</div>
		
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
</body>
</html>

templates/contacto.html
{% extends 'base.html' %}


{% block contenido %}

    <div class="container">
      <div class="row fo">
        <div class="col-md-12">
          <h1>Formulario</h1>
          <hr class="divisor">
          <p>Te invito a contactarme, te respondere a la brevedad</p>
          <p class="text-danger small">Todos los campos son obligatorios</p>
          <p class="bg-success alert-jrc" id="mensajeExito">Mensaje enviado con exito</p>
          <p class="bg-danger alert-jrc" id="mensajeError"></p>
          <form id="jrcForm">
            <div class="form-group">
              <label for="nombre">Nombre</label>
              <input type="text" class="form-control" name="nombre" value="" id="nombre">
            </div>
            <div class="form-group">
              <label for="email">E-mail</label>
              <input type="email" class="form-control" name="email" id="email">
            </div>
            <div class="form-group">
              <label for="asunto">Asunto</label>
              <input type="text" class="form-control" name="asunto" value="" id="asunto">
            </div>
            <div class="form-group">
              <label for="mensaje">Mensaje</label>
              <textarea class="form-control" name="mensaje" id="mensaje" cols="30" rows="10"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Enviar</button>
          </form>
        </div>
      </div>
    </div>


{% endblock %}

templates/navbar.html
        <nav class="navbar">
            <div class="contenedor">
                <a href="http://127.0.0.1:8000/">Inicio</a>
                <a href="#">Sobre Nosotros</a>
                <a href="#">Novedades</a>
                <a href="#">Contacto</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'perfil:logout' %}">Cerrar sesión</a>
                {% else %}
                    <a href="{% url 'perfil:login' %}">Iniciar sesión</a>
                {% endif %}
            </div>
                
        </nav>



   

templates/navbar_a.html
<nav  class="navbar navbar-expand-lg navbar-light " style="background-color: #FFC0CB;" >
      <div class="container-fluid">
        <a class="navbar-brand" href="http://127.0.0.1:8000/">Inicio</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link " aria-current="page" href="http://127.0.0.1:8000/alumnos/lista_alumnos/">Alumnos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:8000/personal/lista_personal/">Personal</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:8000/persona/lista_personas/">Personas</a>

                </li>
                <li class="nav-item"> 
                    <a class="nav-link" href="http://127.0.0.1:8000/contactos/lista_contactos/">Contactos</a>
                </li>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="http://127.0.0.1:8000/admin/login/?next=/admin/">Administrador</a>
                </li>
            </ul>
        </div>
    </div>
    {% if request.user.is_authenticated %}
        <a href="{% url 'perfil:logout' %}">Cerrar sesión</a>
    {% else %}
        <a href="{% url 'perfil:login' %}">Iniciar sesión</a>
    {% endif %}
    
</nav>